"""jira-style task fields

Revision ID: 519fd5018268
Revises: 88f63060cd9d
Create Date: 2026-08-10 17:03:08.700126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519fd5018268'
down_revision: Union[str, Sequence[str], None] = '88f63060cd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing tasks need values before these columns can become NOT NULL.
    # A temporary server default lets PostgreSQL backfill every existing row
    # atomically while preserving the application's Python-side defaults for
    # new Task objects.
    op.add_column(
        'tasks',
        sa.Column(
            'priority', sa.String(length=20), nullable=False,
            server_default=sa.text("'medium'"),
        ),
    )
    op.add_column('tasks', sa.Column('story_points', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column(
        'tasks',
        sa.Column(
            'labels', sa.JSON(), nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
    )
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(
        'fk_tasks_parent_task_id', 'tasks', 'tasks', ['parent_task_id'], ['id']
    )
    # Do not retain database defaults: the ORM owns defaults for new tasks.
    op.alter_column('tasks', 'priority', server_default=None)
    op.alter_column('tasks', 'labels', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_parent_task_id', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'story_points')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
